### ISSUE TITLE
atmel-samd: PulseIn resume trigger_duration is required positional value vs. optional keyword argument.

### ISSUE THREAD

**Issue by tdicola** [adafruit/circuitpython#125]
It looks like trying to call a PulseIn resume without trigger duration specified fails (using the 0.9.7 release)
```
>>> import board
>>> import pulseio
>>> pulses = pulseio.PulseIn(board.D6)
>>> pulses.resume()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: trigger_duration must be int
```
Docs show it as an optional parameter that should default to 0 though: http://circuitpython.readthedocs.io/en/latest/shared-bindings/pulseio/PulseIn.html

**Comment by tdicola** [comment]
Actually it doesn't look like this is a keyword argument.  This fails too:
```
>>> pulses.resume(trigger_duration=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: trigger_duration must be int
```
This succeeds though:
```
>>> pulses.resume(0)
>>> 
```
