### ISSUE TITLE
call to time.struct_time() fails in beta-0

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#1493]
Just tried running some code I have been using for quite awhile on 4.0 alpha but it now breaks.
```
uto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 114, in <module>
  File "code.py", line 79, in <module>
  File "/lib/adafruit_gps.py", line 110, in update
  File "/lib/adafruit_gps.py", line 186, in _parse_gpgga
TypeError: time.struct_time() takes exactly 1 argument
```
has time.struct_time changed?

I'll look at the gps lib but something has changed and broken....

**Comment by jerryneedell** [comment]
If I revert back to this build, the code runs normally.
 ```Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-alpha.5-133-g9678a5a32 on 2019-01-12; Adafruit ItsyBitsy M4 Express with samd51g19
>>> 
```

**Comment by jerryneedell** [comment]
compared CP4.0 Beta to CPython (Python3 on Ubuntu Linux)


```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-beta.0-15-g6be4b07e1 on 2019-01-24; Adafruit Metro M4 Express with samd51j19
>>> 
>>> 
>>> import time
>>> x = time.struct_time((0,0,0,0,0,0,0,0,0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: time.struct_time() takes exactly 1 argument
>>> 
```
```
jerryneedell@Ubuntu-Macmini:~$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> x=time.struct_time((0,0,0,0,0,0,0,0,0))
>>> x
time.struct_time(tm_year=0, tm_mon=0, tm_mday=0, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=0, tm_yday=0, tm_isdst=0)
>>> 
```

**Comment by jerryneedell** [comment]
as suggested by @tannewt  made this chsnge  
```
jerryneedell@Ubuntu-Macmini:~/circuitpython_master/ports/atmel-samd$ git diff
diff --git a/shared-bindings/time/__init__.c b/shared-bindings/time/__init__.c
index f19b972d0..3babe2db4 100644
--- a/shared-bindings/time/__init__.c
+++ b/shared-bindings/time/__init__.c
@@ -84,7 +84,7 @@ MP_DEFINE_CONST_FUN_OBJ_1(time_sleep_obj, time_sleep);
 
 #if MICROPY_PY_COLLECTIONS
 mp_obj_t struct_time_make_new(const mp_obj_type_t *type, size_t n_args, const mp_obj_t *args, mp_map_t *kw_args) {
-    if (n_args != 1 || kw_args != NULL || kw_args->used > 0) {
+    if (n_args != 1 || (kw_args != NULL && kw_args->used > 0)) {
         mp_raise_TypeError(translate("time.struct_time() takes exactly 1 argument"));
     }
     if (!MP_OBJ_IS_TYPE(args[0], &mp_type_tuple) || ((mp_obj_tuple_t*) MP_OBJ_TO_PTR(args[0]))->len != 9) {
```
Seems to have fixed it -- Apparently kw_args is not NULL

```
Adafruit CircuitPython 4.0.0-beta.0-15-g6be4b07e1-dirty on 2019-01-25; Adafruit Metro M4 Express with samd51j19
>>>
>>> import time
>>> x = time.struct_time((0,0,0,0,0,0,0,0,0))
>>> x
struct_time(tm_year=0, tm_mon=0, tm_mday=0, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=0, tm_yday=0, tm_isdst=0)
>>> 
```

and my code using gps and pcf8523 RTC now work as expected.
