### ISSUE TITLE
PyPortal lib broken for TileGrid

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#1646]
I think the latest changes to displayio have broken the PyPortal lib call to TileGrid

I tried the PyPortal EventCountdown example with latest build and it fails
```

Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-beta.3-34-g494a9d382 on 2019-03-13; Adafruit PyPortal with samd51j20
>>> 
>>> import eventcountdown
ESP firmware: bytearray(b'1.2.2\x00')
Set background to  /countdown_background.bmp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "eventcountdown.py", line 29, in <module>
  File "adafruit_pyportal.py", line 252, in __init__
  File "adafruit_pyportal.py", line 363, in set_background
TypeError: extra keyword arguments given
>>> 
```

It works if I revert to a previous build
```

Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-beta.3-15-gcfb54f026 on 2019-03-12; Adafruit PyPortal with samd51j20
>>> 
>>> import eventcountdown
ESP firmware: bytearray(b'1.2.2\x00')
Set background to  /countdown_background.bmp
Getting time from internet!
Connecting to AP Needell Airport
Getting time for timezone America/New_York
struct_time(tm_year=2019, tm_mon=3, tm_mday=13, tm_hour=23, tm_min=2, tm_sec=11, tm_wday=3, tm_yday=72, tm_isdst=None)
Current time: struct_time(tm_year=2019, tm_mon=3, tm_mday=13, tm_hour=23, tm_min=2, tm_sec=11, tm_wday=2, tm_yday=72, tm_isdst=-1)
Time remaining (s): 2800669
32 days, 9 hours, 57 minutes and 49 seconds
Current time: struct_time(tm_year=2019, tm_mon=3, tm_mday=13, tm_hour=23, tm_min=2, tm_sec=21, tm_wday=2, tm_yday=72, tm_isdst=-1)
Time remaining (s): 2800659
32 days, 9 hours, 57 minutes and 39 seconds
```

It looks like the "position" keyword argument was removed from Tilegrid so this line fails:
 https://github.com/adafruit/Adafruit_CircuitPython_PyPortal/blob/master/adafruit_pyportal.py#L364

**Comment by jerryneedell** [comment]
Fixed by 
https://github.com/adafruit/Adafruit_CircuitPython_PyPortal/pull/15
