### ISSUE TITLE
Building with a frozen module that has no tag fails with a confusing error message

### ISSUE THREAD

**Issue by rhooper** [adafruit/circuitpython#1849]
Building with a frozen module that has no tag fails with a confusing error message.

Eg:

```
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
FREEZE ../../frozen/Adafruit_CircuitPython_BusDevice ../../frozen/Adafruit_CircuitPython_CircuitPlayground ../../frozen/Adafruit_CircuitPython_HID ../../frozen/Adafruit_CircuitPython_LIS3DH ../../frozen/CircuitPython_Pixbuf_Neopixel ../../frozen/Adafruit_CircuitPython_Thermistor
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
Traceback (most recent call last):
  File "../../tools/preprocess_frozen_modules.py", line 14, in version_string
    tag = subprocess.check_output('git describe --tags --exact-match', shell=True, cwd=path)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'git describe --tags --exact-match' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../tools/preprocess_frozen_modules.py", line 71, in <module>
    copy_and_process(in_dir, args.out_dir)
  File "../../tools/preprocess_frozen_modules.py", line 54, in copy_and_process
    module_version = version_string(root, valid_semver=True)
  File "../../tools/preprocess_frozen_modules.py", line 17, in version_string
    describe = subprocess.check_output("git describe --tags", shell=True, cwd=path)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'git describe --tags' returned non-zero exit status 128.
make: *** [build-circuitplayground_express/frozen_mpy] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by dhalbert** [comment]
Subsumed as a dupe by #7193.
