### ISSUE TITLE
I2C - TypeError: extra keyword arguments given

### ISSUE THREAD

**Issue by wallarug** [adafruit/circuitpython#2176]
There seems that there is an issue in either i2c_bits.py or i2c_device.py.  When I run the INA219 CircuitPython example, it errors out.  The correct address has been entered as I tried with an incorrect address and I get a different error.

I downloaded the latest version of adafruit_register and put it in the lib/ folder on my CIRCUITPY drive.

**REPL Output**
```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 10, in <module>
  File "/lib/adafruit_ina219.py", line 164, in __init__
  File "/lib/adafruit_ina219.py", line 309, in set_calibration_32V_2A
  File "/lib/adafruit_register/i2c_bits.py", line 88, in __set__
  File "/lib/adafruit_register/i2c_bits.py", line 74, in __set__
  File "adafruit_bus_device/i2c_device.py", line 147, in write_then_readinto
TypeError: extra keyword arguments given
```

**Build Details**
`Adafruit CircuitPython 5.0.0-alpha.4-8-gbd4282a-dirty on 2019-09-17; Robo HAT MM1 with samd51g19`

**Libraries**
https://github.com/adafruit/Adafruit_CircuitPython_BusDevice
https://github.com/wallarug/Adafruit_CircuitPython_INA219

**Comment by ladyada** [comment]
hiya please move this issue to
https://github.com/adafruit/Adafruit_CircuitPython_INA219
since it is not a core circuitpython issue but a library issue! thanx :)
