### ISSUE TITLE
Fix dir for properties so they are not called.

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#2179]
When doing `dir()` on a built-in, the getter is called. This is usually ok but causes issues when the property throws an exception. This was found when diring a `_bleio.Characteristic`.

Stack trace:
```
#4  0x0003785c in mp_call_function_n_kw (fun_in=0xa6188 <bleio_characteristic_get_value_obj>, n_args=1, n_kw=0, args=0x2003f8cc)
    at ../../py/runtime.c:624
#5  0x000382b2 in mp_convert_member_lookup (self=0x2001cdb0, type=0xa621c <bleio_characteristic_type>,
    member=0xa6198 <bleio_characteristic_value_obj>, dest=0x2003f95c) at ../../py/runtime.c:1042
#6  0x000383ae in mp_load_method_maybe (obj=0x2001cdb0, attr=927, dest=0x2003f95c) at ../../py/runtime.c:1085
#7  0x00038480 in mp_load_method_protected (obj=0x2001cdb0, attr=927, dest=0x2003f95c, catch_all_exc=false)
    at ../../py/runtime.c:1118
#8  0x0004ce1c in mp_builtin_dir (n_args=1, args=0x2001d6fc) at ../../py/modbuiltins.c:193
```

**Comment by dhalbert** [comment]
https://github.com/micropython/micropython/issues/4546 is the same issue.
