### ISSUE TITLE
PR #2644 (disable remote editing) is breaking BLE

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#2646]
I was trying a BLE program on the latest master, and ran into this:
```
>>> from adafruit_ble.services.nordic import UARTService
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_ble/services/nordic.py", line 38, in <module>
  File "adafruit_ble/services/nordic.py", line 50, in UARTService
  File "adafruit_ble/uuid/__init__.py", line 74, in __init__
_bleio.BluetoothError: Unknown soft device error: 0002
```
A build from the commit just before #2644 doesn't have this problem.

Tagging @tannewt; I'll investigate too.

**Comment by dhalbert** [comment]
Error 0002 is SD not enabled. The failure is in UUID creation. So the SD was enabled previously before #2644, but is now not enabled implicitly.

**Comment by tannewt** [comment]
Sorry about this! I only tested the advertising demo I'm working on. Will look at the PR now.
