### ISSUE TITLE
makerdiary_nrf52840_mdk_usb_dongle needs very long to flash

### ISSUE THREAD

**Issue by T2brozz** [adafruit/circuitpython#3368]
I'm trying to flash `nRF52 Radio Soft Device` to the usb dongle, but I got this error: `
2020-09-01 20:03:31,019 LIBUSB_ERROR_ACCESS: Unable to connect to trigger interface.

Traceback (most recent call last):
  File "/home/yannes/.local/lib/python3.8/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yannes/.local/lib/python3.8/site-packages/nordicsemi/dfu/dfu_transport_serial.py", line 198, in open
    self.serial_port = Serial(port=self.com_port,
  File "/home/yannes/.local/lib/python3.8/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/yannes/.local/lib/python3.8/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyACM0: [Errno 13] Permission denied: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yannes/.local/bin/nrfutil", line 33, in <module>
    sys.exit(load_entry_point('nrfutil==6.1.0', 'console_scripts', 'nrfutil')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yannes/.local/lib/python3.8/site-packages/nordicsemi/__main__.py", line 1014, in usb_serial
    do_serial(package, port, connect_delay, flow_control, packet_receipt_notification, baud_rate, serial_number, False,
  File "/home/yannes/.local/lib/python3.8/site-packages/nordicsemi/__main__.py", line 970, in do_serial
    dfu.dfu_send_images()
  File "/home/yannes/.local/lib/python3.8/site-packages/nordicsemi/dfu/dfu.py", line 119, in dfu_send_images
    self._dfu_send_image(self.manifest.softdevice)
  File "/home/yannes/.local/lib/python3.8/site-packages/nordicsemi/dfu/dfu.py", line 88, in _dfu_send_image
    self.dfu_transport.open()
  File "/home/yannes/.local/lib/python3.8/site-packages/nordicsemi/dfu/dfu_transport_serial.py", line 202, in open
    raise NordicSemiException("Serial port could not be opened on {0}"
pc_ble_driver_py.exceptions.NordicSemiException: Serial port could not be opened on /dev/ttyACM0. Reason: could not open port /dev/ttyACM0: [Errno 13] Permission denied: '/dev/ttyACM0'
`

After that I tryed it with sudo but now I get 
`2020-09-01 20:03:51,062 No trigger interface found for device with serial number: C96088918EFD, Product ID: 0xCAFE and Vendor ID: 0x1915`
and after that I stuck and nothing is happening.
Can someone is helping me

**Comment by tannewt** [comment]
Hi, for board specific support please contact the manufacturer. Looks like MakerDiary has a support forum here: https://community.makerdiary.com/
