### ISSUE TITLE
ESP32-S2 SD card won't mount?

### ISSUE THREAD

**Issue by emard** [adafruit/circuitpython#3396]
Is SD card supposed to work on ESP32-S2 WROVER?
I pulled latest driver bundle and tried this example to mount
SD card:

https://github.com/emard/esp32ecp5/blob/master/circuitpython/sdmount.py

If SD card is inserted (it has FAT and old ESP32 non-S2 is able to mount),
then ESP32-S2 prints

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sdmount.py", line 31, in <module>
  File "adafruit_sdcard.py", line 116, in __init__
  File "adafruit_sdcard.py", line 177, in _init_card
  File "adafruit_sdcard.py", line 155, in _init_card
OSError: couldn't determine SD card version

if SD card is not inserted then:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sdmount.py", line 31, in <module>
  File "adafruit_sdcard.py", line 116, in __init__
  File "adafruit_sdcard.py", line 177, in _init_card
  File "adafruit_sdcard.py", line 145, in _init_card
OSError: no SD card

**Comment by jepler** [comment]
I think it's likely that it doesn't work due to the ignored value of write_value in common_hal_busio_spi_read, an esp32 flavored version of #3176. This function (at least handling the all-ones value 0xff) is required for SPI SD cards to work.
