### ISSUE TITLE
ESP32-S2 espidf.MemoryError: in _get_socket after running OK for many hours / GETs

### ISSUE THREAD

**Issue by anecdata** [adafruit/circuitpython#3562]
Adafruit CircuitPython 6.0.0-beta.2-58-g40a3d11d6 on 2020-10-11; Saola 1 w/Wrover with ESP32S2
adafruit-circuitpython-bundle-6.x-mpy-20201013

Exception after a day or two of running (5-10 GETs per hour). IDF "largest block" typically is around 30KB right before a successful GET, I've seen "largest block" as low as 11KB right before a GET that fails for other reasons (e.g., " Unable to read HTTP response").

```
IDF total 167968 free 22132 largest 14732
Traceback (most recent call last):
  File "code.py", line 1923, in <module>
  File "code.py", line 511, in http_get
  File "code.py", line 504, in http_get
  File "adafruit_requests.py", line 555, in get
  File "adafruit_requests.py", line 535, in request
  File "adafruit_requests.py", line 440, in _get_socket
espidf.MemoryError: 
```

I'll try to get a minimal example to demonstrate.

**Comment by anecdata** [comment]
Change in IDF memory behavior from Requests 1.7.2 to 1.7.3/1.7.4...

This is maybe better as a Requests issue, perhaps related to [https://github.com/adafruit/Adafruit_CircuitPython_Requests/issues/47](https://github.com/adafruit/Adafruit_CircuitPython_Requests/issues/47)

But perhaps also an indication that we are near the edge on IDF memory.
```
Saola 1 w/Wrover with ESP32S2
6.0.0-rc.0 on 2020-10-16
adafruit-circuitpython-bundle-6.x-mpy-20201031
Requests 1.7.4 or Requests 1.7.3 (Requests 1.7.2 is fine initially)
```

Looks like it has plenty of IDF memory before the the very first GET in my code, but gets exception:
```
total 165952 free 48940 largest 47652
Traceback (most recent call last):
  File "code.py", line 1430, in <module>
  File "code.py", line 511, in http_get
  File "code.py", line 504, in http_get
  File "/lib/adafruit_requests.py", line 555, in get
  File "/lib/adafruit_requests.py", line 535, in request
  File "/lib/adafruit_requests.py", line 440, in _get_socket
espidf.MemoryError: 
```

**Comment by anecdata** [comment]
Closing. I haven't seen this for a couple of months, probably addressed by other improvements.
