### ISSUE TITLE
OneWire on STM32F405 not working

### ISSUE THREAD

**Issue by CrossLAN** [adafruit/circuitpython#3935]
DS18B20 OneWire sensors connected to STM32F405 Pin D5 (I tried also D6, etc.) failed. Pull Up resistor is not the issue. 

**ow_bus.scan() shows different behavior in case of:**
a) pin is not connected or
b) sensor or multiple sensors are connected

Case a) IndexError: list index out of range
Case b) nothing is showing up

Same code (with different pins) and same sensors with Metro Express and Playground Express boards is working well.

Tried "[Simple Test](https://github.com/adafruit/Adafruit_CircuitPython_OneWire/blob/master/examples/onewire_simpletest.py
)" for one wire [from GitHub](https://github.com/adafruit/Adafruit_CircuitPython_OneWire/blob/master/examples/onewire_simpletest.py
)

**Even the pull up resistor is not the issue because it works on other boards the result is:**
```
code.py output:
Resetting bus...Traceback (most recent call last):
  File "code.py", line 14, in <module>
RuntimeError: Nothing found on bus.
```

**If I remove the one wire sensors the result is:**
```
code.py output:
Resetting bus...OK.
Scanning for devices...Traceback (most recent call last):
  File "code.py", line 18, in <module>
  File "adafruit_onewire/bus.py", line 158, in scan
RuntimeError: Maximum device count of 10 exceeded.
```

Perhaps stm32duino / Arduino_Core_STM32 group is working on something similar (no. 412) and maybe the link is helpful even it is not CircuitPython related: [Support OneWire device (ex: DS1822) #412](https://github.com/stm32duino/Arduino_Core_STM32/issues/412)

**Comment by notDIRK** [comment]
Closing this as stale — I no longer have the STM32F405 board, so I can't verify whether this still applies to current CircuitPython. Given how much has changed since 8.x, an unverified five-year-old report isn't much use sitting in the tracker.

If anyone runs into OneWire trouble on STM32F4 again, this can be reopened or filed fresh with current details.

**Comment by dhalbert** [comment]
@notDIRK My guess is that this is still broken, because the code in question hasn't changed. But I'll open a new issue so you're not in the loop on this.
