### ISSUE TITLE
native BusDevice breaks I2C if LONGINT_IMP = NONE

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#4109]
See https://github.com/adafruit/Adafruit_CircuitPython_LIS3DH/issues/67

```
Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 6.2.0-beta.1-23-g0c0b51711 on 2021-02-01; HalloWing M0 Express with samd21g18
>>> import lis3dh_simpletest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lis3dh_simpletest.py", line 16, in <module>
  File "adafruit_lis3dh.py", line 332, in __init__
OverflowError: small int overflow
>>> 
```
The issue is resolved if native BusDevice is not used. 
Can also resolve by building with LONGINT_IMPL = MPZ
But then it won’t fit in Flash unless something else is removed.

**Comment by tannewt** [comment]
Fixed by #4112
