### ISSUE TITLE
non-TLS HTTP requests fail

### ISSUE THREAD

**Issue by anecdata** [adafruit/circuitpython#4151]
Opening a fresh issue, based on comments in adafruit/Adafruit_CircuitPython_Requests#63:

On CicruitPython (since PR#4049), non-TLS HTTP requests fail:
```
import sys
import time
import socketpool
# import ssl
import wifi
import secrets
import adafruit_requests as requests
from secrets import secrets

wifi.radio.connect(secrets["ssid"], secrets["password"])
print("RSSI", wifi.radio.ap_info.rssi)

socket = socketpool.SocketPool(wifi.radio)
# http = requests.Session(socket, ssl.create_default_context())  # this doesn't work now for HTTP
http = requests.Session(socket)

URL = "http://wifitest.adafruit.com/testwifi/index.html"  # doesn't work
# URL = "http://httpbin.org/get"  #  doesn't work
# URL = "https://httpbin.org/get"  # works

while True:
    print("-" * 40)
    try:
        response = http.get(URL)
    except (OSError) as e:
        sys.print_exception(e)
    except (RuntimeError) as e:
        sys.print_exception(e)
    try:
        print(response.status_code, response.reason)
        trash = response.text
        trash = None
        response.close()
    except (NameError) as e:
        sys.print_exception(e)
    time.sleep(5)
```
results in:
```
        Traceback (most recent call last):
          File "code.py", line 26, in <module>
          File "code.py", line 24, in <module>
          File "/lib/adafruit_requests.py", line 597, in get
          File "/lib/adafruit_requests.py", line 560, in request
          File "/lib/adafruit_requests.py", line 429, in _get_socket
        RuntimeError: Sending request failed
```
It's not entirely clear to me if this is an issue with Requests or `socketpool`.

**Comment by anecdata** [comment]
Closing, fixed by #4148.
