### ISSUE TITLE
ESP32S2 -- Cannot access I2C after reboot

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#4178]
on a metro-esp32s2 -- CP and libraries all updated this morning.
After a hard reset I can access I2C normally, but after soft reboot or deep sleep the access fails to find the I2C device
This example uses board.I2C, but it fails the same with busio.I2C

```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 6.2.0-beta.2 on 2021-02-11; Adafruit Metro ESP32S2 with ESP32S2
>>>
>>> import shtc3_simpletest
Temperature: 20.6 C
Humidity: 28.8 %

Temperature: 20.6 C
Humidity: 28.8 %

Temperature: 20.6 C
Humidity: 28.8 %

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "shtc3_simpletest.py", line 17, in <module>
KeyboardInterrupt:
>>>
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.


Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 6.2.0-beta.2 on 2021-02-11; Adafruit Metro ESP32S2 with ESP32S2
>>> import shtc3_simpletest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "shtc3_simpletest.py", line 10, in <module>
  File "adafruit_shtc3.py", line 89, in __init__
ValueError: No I2C device at address: 70
>>>

**Comment by jerryneedell** [comment]
closing -- duplicate of #4147 -- it's deja vu -- all over again....
