### ISSUE TITLE
usb_hid not working 

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#4724]
I just built CP forom the tip of main for the neopixel_trinkey_m0
but now usb_hid is not working.  
I had the same issue on the neopixel_trinkey_m0 and the pirkey_m0

Edited to add -- I get the same error on a QTPY_RP2040

```

Adafruit CircuitPython 7.0.0-alpha.1-1088-g2fe1df466 on 2021-05-07; Adafruit NeoPixel Trinkey M0 with samd21e18
>>> import usb_hid
>>> from adafruit_hid.keyboard import Keyboard
>>> keyboard = Keyboard(usb_hid.devices)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_hid/keyboard.py", line 65, in __init__
  File "adafruit_hid/keyboard.py", line 113, in release_all
OSError: USB Busy
>>> 
```

**Comment by chowha** [comment]
Same with me using the RP Pico using mouse in the latest build (adafruit-circuitpython-raspberry_pi_pico-en_US-20210507-f761292.uf2)

Seems to fail in the same place but in mouse.py when initializing at the section below. 
 
 try:
            self._send_no_move()
        except OSError:
            time.sleep(1)
            self._send_no_move()
            
With the error:

Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/lib/adafruit_hid/mouse.py", line 49, in __init__
  File "/lib/adafruit_hid/mouse.py", line 143, in _send_no_move
OSError: USB Busy
>>>
