### ISSUE TITLE
bytes and bytesarray do not validate arguments properly

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#4934]
This is present in 6.3.0 and 7.0.0. I didn't test earlier versions yet. `bytes(1,2,3)` should raise an error, but it doesn't.
```py
>>> bytes(1,2,3)
b'\x00'
>>> bytes((1,2,3))
b'\x01\x02\x03'
```
Same is true for `bytearray`. `bytes()` does not take the contents as a variable number of arguments. It needs a sequence as the first arg.
CPython:
```py
>>> bytes(1,2,3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: bytes() argument 2 must be str, not int
```
MicroPython (tested on 1.12 and 1.16):
```py
>>> bytes(1,2,3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: wrong number of arguments
```

**Comment by dhalbert** [comment]
This is more complicated than it first appears:
```py
>>> bytearray(1,2,3)
bytearray(b'\x00')
>>> bytearray(1,2,3,4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: function expected at most 3 arguments, got 4
>>> bytes(1,2,3,4)
b'\x00'
```
`bytearray` and `bytes` are treated differently.

I think the reason the length check for `bytes()` is not done is due to #2220. We'll need to do the check without undoing that fix.
