### ISSUE TITLE
Onboard NeoPixel still in use after filesystem change triggered restart.

### ISSUE THREAD

**Issue by rsbohn12** [adafruit/circuitpython#5001]
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0-alpha.4 on 2021-07-08; Adafruit Metro M4 Express with samd51j19
```

### Code/REPL

```python
import time
import board
from neopixel import NeoPixel

pixel = NeoPixel(board.NEOPIXEL, 1, brightness=0.3)

lightshow = [0xFF0000, 0xCCCC00, 0x00CC00, 0xCCCC00]
step = 0
while True:
    pixel[0] = lightshow[step % len(lightshow)]
    time.sleep(0.1)
    step += 1
```

### Behavior

```python
Traceback (most recent call last):
  File "code.py", line 14, in <module>
  File "neopixel.py", line 127, in __init__
ValueError: NEOPIXEL in use
```
When a filesystem change triggers a reset the above error appears.

### Description

Using Ctrl-C Ctrl-D does work. The NEOPIXEL pin is not in use when code.py starts.

It is annoying to have to reset the board after saving a code change.

I may resort to this:

```python
try:
    pixel = NeoPixel(board.NEOPIXEL, 1, brightness=0.3)
except ValueError:
    print("Sorry, neopixel didn't get reset.\nHang on...")
    import microcontroller
    microcontroller.reset()
```

**Comment by rsbohn12** [comment]
Probably the same root cause as https://github.com/adafruit/circuitpython/issues/4997.
