### ISSUE TITLE
7.0.0-Alpha.4 Importing adafruit_circuitplayground.expresss Results in Error

### ISSUE THREAD

**Issue by robertgallup** [adafruit/circuitpython#5009]
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0-alpha.4 on 2021-07-08; Adafruit CircuitPlayground Express with samd21g18
```

### Code/REPL

```python
import adafruit_circuitplayground.express
```

### Behavior

main.py output:
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "adafruit_circuitplayground/__init__.py", line 12, in <module>
  File "adafruit_circuitplayground/express.py", line 31, in <module>
  File "adafruit_circuitplayground/circuit_playground_base.py", line 34, in <module>
ImportError: no module named 'gamepad'

### Description

After updating CircuitPython to v7.0.0_alpha4 the circuit playground express library references the gamepad module which doesn't seem to exist.

**Comment by kattni** [comment]
This is an issue with the Circuit Playground library. I'm looking into it now.
