### ISSUE TITLE
supervisor.get_previous_traceback() not working

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#5332]
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0-rc.1-61-gcf5c32be3 on 2021-09-12; Adafruit Feather nRF52840 Express with nRF52840
```

### Code/REPL

```python
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Sent Hello World message!
Waiting for packets...
Traceback (most recent call last):
  File "code.py", line 57, in <module>
  File "adafruit_rfm9x.py", line 788, in receive
  File "adafruit_rfm9x.py", line 638, in rx_done
  File "adafruit_rfm9x.py", line 360, in _read_u8
  File "adafruit_rfm9x.py", line 355, in _read_into
KeyboardInterrupt: 

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-rc.1-61-gcf5c32be3 on 2021-09-12; Adafruit Feather nRF52840 Express with nRF52840
>>> import supervisor
>>> supervisor.get_previous_traceback()
>>>
```

### Behavior

supervisor.get_previous_traceback() is not returning anything?

Prior to RC.1 I was seeing a report of the traceback from the last error

**Comment by jerryneedell** [comment]
here is a better example on a fether M4 express
with an older version of CP -- beta.0

```
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 33, in <module>
  File "adafruit_rfm9x.py", line 252, in __init__
RuntimeError: Failed to find rfm9x with expected version -- check wiring

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-beta.0-44-gd8b3d5af0 on 2021-08-25; Adafruit Feather M4 Express with samd51j19
>>> import supervisor
>>> supervisor.get_previous_traceback()
'Traceback (most recent call last):\r\n  File "code.py", line 33, in <module>\r\n  File "adafruit_rfm9x.py", line 252, in __init__\r\nRuntimeError: Failed to find rfm9x with expected version -- check wiring\n'
>>> 
```


with rc.1
```
Adafruit CircuitPython 7.0.0-rc.1-61-gcf5c32be3 on 2021-09-12; Adafruit Feather M4 Express with samd51j19
>>> 
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 33, in <module>
  File "adafruit_rfm9x.py", line 252, in __init__
RuntimeError: Failed to find rfm9x with expected version -- check wiring

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-rc.1-61-gcf5c32be3 on 2021-09-12; Adafruit Feather M4 Express with samd51j19
>>> import supervisor
>>> supervisor.get_previous_traceback()
>>>
