### ISSUE TITLE
I2C_TFT_POWER pin in use error when using in code

### ISSUE THREAD

**Issue by kattni** [adafruit/circuitpython#5903]
### CircuitPython version

```python
Adafruit CircuitPython 7.1.1 on 2022-01-14; Adafruit Feather ESP32-S2 TFT with ESP32S2
Adafruit CircuitPython 7.2.0-alpha.1 on 2021-12-29; Adafruit Feather ESP32-S2 TFT with ESP32S2
Adafruit CircuitPython 7.2.0-alpha.1-181-gf2713afff on 2022-01-21; Adafruit Feather ESP32-S2 TFT with ESP32S2
```

### Code/REPL

```python
import time
import board
import digitalio
from adafruit_lc709203f import LC709203F, PackSize

# Pull the I2C power pin high
i2c_power = digitalio.DigitalInOut(board.I2C_TFT_POWER)
i2c_power.switch_to_output()
i2c_power.value = True

# Create sensor object, using the board's default I2C bus.
battery_monitor = LC709203F(board.I2C())
battery_monitor.pack_size = PackSize.MAH400

while True:
    print("Battery Percent: {:.2f} %".format(battery_monitor.cell_percent))
    print("Battery Voltage: {:.2f} V".format(battery_monitor.cell_voltage))
    time.sleep(2)
```

### Behavior

Code fails to run with the following error on 7.2.0-alpha.1 and 7.2.0-alpha.1-181-gf2713afff (current latest on S3).
```
Traceback (most recent call last):
  File "code.py", line 12, in <module>
ValueError: I2C_TFT_POWER in use
```
Running the following in the REPL fails as well on both latest and 7.2.0-alpha.1:
```
Adafruit CircuitPython 7.2.0-alpha.1-181-gf2713afff on 2022-01-21; Adafruit Feather ESP32-S2 TFT with ESP32S2
>>> import board
>>> import digitalio
>>> i2c_power = digitalio.DigitalInOut(board.I2C_TFT_POWER)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: I2C_TFT_POWER in use
>>>
```

On 7.1.1, code runs successfully with AND without the `I2C_TFT_POWER` pin setup code.

### Description

On 7.2.0-alpha.1-181-gf2713afff and 7.2.0-alpha.1:
When attempting to set up the `I2C_TFT_POWER` pin in code.py, it fails to run with a `ValueError: I2C_TFT_POWER in use` error.

Without the power pin setup code included, the board crashes into the hardfault handler on startup. It is my understanding that CircuitPython handles enabling the power pin internally, and so I tried to run the code without the power pin enabling code, and it crashes into the hardfault handler. So that's apparently not correct either.

On 7.1.1:
Code runs successfully.

**Comment by anecdata** [comment]
Same issue on the non-TFT Feather:
```py
Adafruit CircuitPython 7.2.0-alpha.1-224-gac7a80753 on 2022-01-26; Adafruit Feather ESP32S2 with ESP32S2
>>> import board
>>> import digitalio
>>> 
>>> i2c_power_control = digitalio.DigitalInOut(board.I2C_POWER_INVERTED)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: I2C_POWER_INVERTED in use
```
