### ISSUE TITLE
DS3231 on ESP32-S2 has I2C problems on versions later than 7.1.1

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#5934]
Simple device addressing sometimes fails. Testing on a Metro ESP32-S2:
```py
>>> import board, adafruit_ds3231
>>> d = adafruit_ds3231.DS3231(board.I2C())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_ds3231.py", line 143, in __init__
  File "adafruit_bus_device/i2c_device.py", line 50, in __init__
  File "adafruit_bus_device/i2c_device.py", line 163, in __probe_for_device
ValueError: No I2C device at address: 0x68
```
On the other hand, somtimes it works:
```py
>>> import adafruit_ds3231
>>> d = adafruit_ds3231.DS3231(board.I2C())
>>> d.temperature
22.75
```
I am trying to make this reproducible. Not sure what triggers the failures. I have power-cycled completely, used with and without another sensor attached, etc.

Not sure if this is related to #5680.

**Comment by dhalbert** [comment]
I am now seeing crashes sometimes reminiscent of #5680 (but not going into safe mode). This is with a build that already incorporates #5854.
