### ISSUE TITLE
problem post 1.18 merge: adafruit_bus_device module not working

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#6066]
When I use the latest build for the feather_m0_rfm9x it fails when importing  the bus_ddevce module
```

Adafruit CircuitPython 7.3.0-alpha.0 on 2022-02-19; Adafruit Feather M0 RFM9x with samd21g18
>>> import adafruit_rfm9x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_rfm9x.py", line 17, in <module>
ImportError: no module named 'adafruit_bus_device.spi_device'
>>> 
```

If I upload the python version of the library from the 7.x bundle, it works .

```
jerryneedell@jerryneedell-ubuntu-macmini:~/bundle$ cp -r 7.x/lib/adafruit_bus_device /media/jerryneedell/CIRCUITPY/
```
then
```

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.3.0-alpha.0 on 2022-02-19; Adafruit Feather M0 RFM9x with samd21g18
>>> 
>>> import adafruit_rfm9x
>>> 


```

It also does not work work if I turn off the CIRCUITPY_BUSDEVICE in the mpconfiboard.mk file and add the frozen module Adafruit_CIrcuitPython_BusDevice (I am also adding the sdcardio module here for another test)
```
mel-samd$ git diff
diff --git a/ports/atmel-samd/boards/feather_m0_rfm9x/mpconfigboard.mk b/ports/atmel-samd/boards/feather_m0_rfm9x/mpconfigboard.mk
index 4003dd67f..dc875b52d 100644
--- a/ports/atmel-samd/boards/feather_m0_rfm9x/mpconfigboard.mk
+++ b/ports/atmel-samd/boards/feather_m0_rfm9x/mpconfigboard.mk
@@ -19,7 +19,9 @@ CIRCUITPY_RTC = 0
 CIRCUITPY_USB_MIDI = 0
 CIRCUITPY_USB_HID = 0
 CIRCUITPY_TOUCHIO = 0
-CIRCUITPY_BUSDEVICE = 1
+CIRCUITPY_BUSDEVICE = 0
+CIRCUITPY_SDCARDIO = 1
 
 # Include these Python libraries in firmware.
+FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_BusDevice
 FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_RFM9x
```

```

Adafruit CircuitPython 7.2.0-alpha.0-205-g918145f76-dirty on 2022-02-19; Adafruit Feather M0 RFM9x with samd21g18
>>> import adafruit_rfm9x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_rfm9x.py", line 17, in <module>
ImportError: no module named 'adafruit_bus_device'
>>> 
>>> help('modules')
__main__          collections       os                supervisor
adafruit_rfm9x    digitalio         pwmio             sys
analogio          gc                rainbowio         time
array             math              random            usb_cdc
board             microcontroller   sdcardio
builtins          micropython       storage
busio             neopixel_write    struct
Plus any modules on the filesystem
>>> 

```

The module does not get included

Did I do something wrong in this build -

```
tmel-samd$ make BOARD=feather_m0_rfm9x -j8
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
mkdir -p build-feather_m0_rfm9x/genhdr
FREEZE ../../frozen/Adafruit_CircuitPython_BusDevice ../../frozen/Adafruit_CircuitPython_RFM9x
MKMANIFEST ../../frozen/Adafruit_CircuitPython_BusDevice ../../frozen/Adafruit_CircuitPython_RFM9x
(cd build-feather_m0_rfm9x/frozen_mpy && find * -name \*.py -exec printf 'freeze_as_mpy("frozen_mpy", "%s")\n' {} \; )> build-feather_m0_rfm9x/manifest.py.tmp && mv -f build-feather_m0_rfm9x/manifest.py.tmp build-feather_m0_rfm9x/manifest.py
GEN build-feather_m0_rfm9x/genhdr/moduledefs.h
QSTR updated
MPY adafruit_rfm9x.py
GEN build-feather_m0_rfm9x/frozen_content.c

185544 bytes used, 2616 bytes free in flash firmware space out of 188160 bytes (183.75kB).
9836 bytes used, 22932 bytes free in ram for stack and heap out of 32768 bytes (32.0kB).

Converted to uf2, output size: 371200, start address: 0x2000
Wrote 371200 bytes to build-feather_m0_rfm9x/firmware.uf2
```

**Comment by jerryneedell** [comment]
This very strange:
I can import adafruit_bme680  (an I2c device,  but not adafruit_rfm9x (an spi device)
but both use adafruit_bus_device....
I am confused

**Comment by dhalbert** [comment]
Do you see this problem with 7.2.0-rc.0?

7.3.0-alpha.0 merged in some new code from MicroPython for freezing modules as part of the merge of MicroPython 1.18. The merged code may be broken in some way.

Try building off the 7.2.x branch for a bit if you want to experiment with freezing things to avoid the merge.

**Comment by jerryneedell** [comment]
I'll try that -- but do you have any idea why I can import bme680 but not rfm9x?

**Comment by jerryneedell** [comment]
Also it the core bus device module supposed to be useable any more?

**Comment by dhalbert** [comment]
>I'll try that -- but do you have any idea why I can import bme680 but not rfm9x?

bme680 does `from adafruit_bus_device import spi_device` conditionally, in the constructor. rfm9x does `import adafruit_bus_device.spi_device as spidev` at the top level, and it does the rename as well. I have no idea why this would make a difference, but it is a difference to be investigated.

>Also is the core bus device module supposed to be useable any more?

Sure, it's supposed to be.
