### ISSUE TITLE
Can't upload files on HUZZAH when main.py is present

### ISSUE THREAD

**Issue by deshipu** [adafruit/circuitpython#636]
I just tried using CircuitPython on a HUZZAH — I got the released binaries for 2.2.3 and used ampy to upload files to it. Everything works fine until you upload `main.py`, after that ampy is no longer able to upload anything. It waits a long time, and finally crashes with:

```
b'#5 ets_task(40100164, 3, 3fff8380, 4)\r\nboot.py output:\r\nmain.py output:\r\nTraceback (most recent call last):\r\n  File "main.py", line 1, in <module>\r\n  File "menu.py", line 4, in <module>\r\n  File "pew.py", line 1, in <module>\r\nKeyboardInterrupt: \r\n\r\n\r\nPress any key to enter the REPL. Use CTRL-D to soft reset.\r\n'
Traceback (most recent call last):
  File "/home/sheep/.local/bin/ampy", line 11, in <module>
    sys.exit(cli())
  File "/home/sheep/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sheep/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sheep/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sheep/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sheep/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sheep/.local/lib/python2.7/site-packages/ampy/cli.py", line 208, in put
    board_files.put(remote, infile.read())
  File "/home/sheep/.local/lib/python2.7/site-packages/ampy/files.py", line 129, in put
    self._pyboard.enter_raw_repl()
  File "/home/sheep/.local/lib/python2.7/site-packages/ampy/pyboard.py", line 202, in enter_raw_repl
    raise PyboardError('could not enter raw repl')
ampy.pyboard.PyboardError: could not enter raw repl
```
The only way to make it work again is to delete `main.py` from the REPL.

**Comment by deshipu** [comment]
Of course I forgot to add, that `main.py` contains an infinite loop.
