### ISSUE TITLE
Potential memory leak when loading bitmaps in sequence on the MatrixPortal

### ISSUE THREAD

**Issue by JeremiahDuane** [adafruit/circuitpython#6585]
### CircuitPython version

```python
Adafruit CircuitPython 7.3.1 on 7-12-2022; Matrix Portal M4
```

### Code/REPL

```python
# SPDX-FileCopyrightText: 2020 John Park for Adafruit Industries
#
# SPDX-License-Identifier: MIT

# Metro Matrix Clock
# Runs on Airlift Metro M4 with 64x32 RGB Matrix display & shield
import gc
import json
import time
import board
import displayio

from adafruit_display_text.bitmap_label import Label as BitmapLabel
from adafruit_display_text.label import Label as Label
from adafruit_bitmap_font import bitmap_font
from adafruit_matrixportal.network import Network
from adafruit_matrixportal.matrix import Matrix
from digitalio import DigitalInOut, Direction, Pull

# Get wifi details and more from a secrets.py file
try:
    from secrets import secrets
except ImportError:
    print("WiFi secrets are kept in secrets.py, please add them there!")
    raise
print("    Metro Minimal Clock")
print("Time will be set for {}".format(secrets["timezone"]))

# -------------------------------------------------- Setup : Start -------------------------------------------------
print(f"0: Memory : {gc.mem_free()}")

matrix = Matrix()
display = matrix.display
display.refresh(minimum_frames_per_second=0)

network = Network(status_neopixel=board.NEOPIXEL, debug=False)

btnUp = DigitalInOut(board.BUTTON_UP)
btnUp.direction = Direction.INPUT
btnUp.pull = Pull.UP

btnDown = DigitalInOut(board.BUTTON_DOWN)
btnDown.direction = Direction.INPUT
btnDown.pull = Pull.UP

# ----------------- Globals ------------------

TIME_FONT = bitmap_font.load_font("/fonts/pixelclock-main-24.bdf")
DATE_FONT = bitmap_font.load_font("/fonts/pixelclock-subtitle-7.bdf")
DEFAULT_BITMAP = displayio.OnDiskBitmap("/bmps/blank.bmp")

BLINK = False
SHOW_DAY_OF_WEEK = False
SHOW_NOTIFICATION = False
NOTIFICATION_IS_NEW = False
NOTIFICATION_IS_UNREAD = False

NOTIFICATION_MESSAGE = None
CURRENT_BITMAP1 = None
CURRENT_BITMAP2 = None
# ----------------- Clock Group ------------------

group = displayio.Group() 
display.show(group)

#Add loading Screen
scene_tile_grid = displayio.TileGrid(DEFAULT_BITMAP, pixel_shader=DEFAULT_BITMAP.pixel_shader)
debug_label = Label(DATE_FONT, x=16, y=16, text="Loading...")

group.append(scene_tile_grid)
group.append(debug_label)

time_label_shadow       = Label(TIME_FONT, x=1 , y=8)
time_label              = Label(TIME_FONT, x=1 , y=9)
underline_label         = Label(TIME_FONT, x=2 , y=9, text = "___")
underline_shadow_label  = Label(TIME_FONT, x=2 , y=8, text = "___")
period_label            = Label(TIME_FONT, x=42, y=8)
date_label              = Label(DATE_FONT, x=3 , y=26)
notification_label      = Label(TIME_FONT, x=55, y=8)

group.append(time_label_shadow)
group.append(time_label)
group.append(underline_label)
group.append(underline_shadow_label)
group.append(period_label)
group.append(date_label)   
group.append(notification_label)

#Remove loading screen...
del group[0]
gc.collect()

print(f"1: Memory : {gc.mem_free()}")
# ----------------- Notification Group ------------------

notification_group = displayio.Group()
notification_scene_tile_grid = displayio.TileGrid(DEFAULT_BITMAP, pixel_shader=DEFAULT_BITMAP.pixel_shader)

notification_label_text = BitmapLabel(DATE_FONT, x=0, y=2)

notification_group.append(notification_scene_tile_grid)
notification_group.append(notification_label_text)

# -------------------------------------------------- Setup : End -------------------------------------------------

# -------------------------------------------------- Notification : Start -------------------------------------------------

class Notification:    
    def __init__(self, id, content, date):      
        self.id = id            
        self.content = content            
        self.date = date             
    def setId(self, id):
        self.id = id
    def getId(self):    
        return self.id
    def setContent(self, content):
        self.content = content
    def getContent(self):    
        return self.content
    def setDate(self, date):
        self.date = date
    def getDate(self):    
        return self.date

def check_notifications():
    global NOTIFICATION_IS_UNREAD
    global NOTIFICATION_IS_NEW
    global NOTIFICATION_MESSAGE

    # Emulate the api call for testing...
    r = '{"messages": [{"content": "Inspirational message. Lorem ipsum lorem ipsum doreafud fam dafeifiea mfaiefm eiafm ","eventId": "663c7f94-945f-47bc-99b5-fd6d2b0bddb3","date": "2023-03-01T19:10:10.000"},{"content": "Inspirational message. 5, but with a loooooooot of sauce safjdk fajdf akdf adhk fj kadfh afdkjhf jdkaf hdjklfa hdjfkla hdfjkladh faldkjf hasdlkf jashd","eventId": "9b315fb8-741f-438c-ae21-b21fd24dee67","date": "2023-02-02T14:10:10.000"}]}'
    data = json.loads(r)
    # #END of test #1 

    network.connect()
    requests = network.requests
    if requests != None:
        # url = secrets["api_read-unread"]
        # r = requests.post(url, data={}, headers={})
        # data = r.json()
        # r.close()

        messages = data['messages']
        if len(messages) > 0:
            for message in messages:
                notification = Notification(message["eventId"], message["content"], message["date"])

                # Only store the newest message.
                if NOTIFICATION_MESSAGE == None or notification.getDate() > NOTIFICATION_MESSAGE.getDate():
                    NOTIFICATION_MESSAGE = notification
                    NOTIFICATION_IS_NEW = True

                NOTIFICATION_IS_UNREAD = True

                del notification
        
        del messages
        del r
        del data
        gc.collect()

    
# -------------------------------------------------- Notification : End -------------------------------------------------

# -------------------------------------------------- Clock : Start -------------------------------------------------

class Scene:    
    def __init__(self, primaryColor, secondaryColor, bmp, bmp2=None):      
        self.primaryColor = primaryColor            
        self.secondaryColor = secondaryColor            
        self.bmp = bmp                                  
        self.bmp2 = bmp2        
    def setBMP(self, bmp):
        self.bmp = bmp
    def getBMP(self):    
        return self.bmp
    def setBMP2(self, bmp2):
        self.bmp = bmp2
    def getBMP2(self):    
        return self.bmp2
    def setPrimaryColor(self, primaryColor):
        self.primaryColor = primaryColor
    def getPrimaryColor(self):    
        return self.primaryColor     
    def setSecondaryColor(self, secondaryColor):
        self.secondaryColor = secondaryColor
    def getSecondaryColor(self):    
        return self.secondaryColor 

SCENES = [
    Scene(0xFFFFFF, 0xFFFFFF, "/bmps/blank.bmp", "/bmps/blank.bmp"),                 # -0-  Notification 
    Scene(0xFFFFFF, 0x40FFFF, "/bmps/snowman_1.bmp", "/bmps/snowman_2.bmp"),         # -1-  January Snowman
    Scene(0xFF9000, 0x856035, "/bmps/sunflower_1.bmp", "/bmps/sunflower_2.bmp"),     # -8-  August Sunflowers
    Scene(0xFFFFFF, 0x40FFFF, "/bmps/wreath_1.bmp", "/bmps/wreath_2.bmp")            # -12- December Wreath
]

def update_clock(year=None, month=None, day=None, hours=None, minutes=None, seconds=None, weekday=None, period=None, scene=None):  
    # ------------------- Clockface : START -------------------
    global NOTIFICATION_IS_UNREAD
    global NOTIFICATION_IS_NEW
    global NOTIFICATION_MESSAGE
    now = time.localtime()
    
    if year is None:
        year = now[0]
    if month is None:
        month = now[1]
    if day is None:
        day = now[2]
    if hours is None:
        hours = now[3]
    if minutes is None:
        minutes = now[4]
    if seconds is None:
        seconds = now[5]
    if weekday is None:
        weekday = now[6]

    if hours > 11:  # Handle times later than 12:59
        periodLabel = "PM"
    else:
        periodLabel = "AM"  
    if hours > 12:  # Handle times later than 12:59
        hours -= 12
    elif not hours:  # Handle times between 0:00 and 0:59
        hours = 12

    timeLabel =  "{zero}{hours}{colon}{minutes:02d}".format(
        zero="0" if hours < 10 else "", 
        hours=hours, minutes=minutes,
        colon=" " if BLINK else ":"
    )
    if SHOW_DAY_OF_WEEK: 
        daysOfWeek = ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"]
        dateLabel =  "{dayOfWeek}. {zero}{day}-{zero1}{month}".format(
            zero="0" if day < 10 else "", 
            zero1="0" if month < 10 else "",
            month=month,
            dayOfWeek=daysOfWeek[weekday],
            day=day
        )
    else:
        dateLabel =  "{zero}{day}.{zero1}{month}.{year}".format(
            zero="0" if day < 10 else "", zero1="0" if month < 10 else "", year=year, month=month, day=day
        )
    
    # ----------------- Update Fields : START ------------------
    #Periodically check and see if there is a new season/theme for the scene. 
    #DO NOT RELEASE: Hardcoded as true to test update. 
    if True or (hours == 0 and minutes == 0 and seconds == 0): 
        if month == 7:
            scene = SCENES[2]
        else: 
            scene = SCENES[0]

        print(f"2: Memory : {gc.mem_free()}")
        CURRENT_BITMAP1 = displayio.OnDiskBitmap(scene.getBMP())
        CURRENT_BITMAP2 = displayio.OnDiskBitmap(scene.getBMP2())
        
        underline_label.color = scene.getPrimaryColor()
        time_label.color = scene.getPrimaryColor()
        date_label.color = scene.getPrimaryColor()
        period_label.color = scene.getPrimaryColor()
        time_label_shadow.color = scene.getSecondaryColor()
        underline_shadow_label.color = scene.getSecondaryColor()

    group[0] = displayio.TileGrid(CURRENT_BITMAP1 if BLINK else CURRENT_BITMAP2, pixel_shader=CURRENT_BITMAP1.pixel_shader)

    time_label_shadow.text = timeLabel
    time_label.text = timeLabel
    date_label.text = dateLabel
    period_label.text = periodLabel

    if NOTIFICATION_IS_NEW and BLINK:
        notification_label.text = "Q" #Heart Icon
    else:
        notification_label.text = " "

    # ----------------- Notification Setup : START ------------------
    #Get the bit width of each character
    def getBitWidth(char):
        if char in ["M", "W", "^"]:
            return 6
        elif char in ["N"]:
            return 5
        elif char in [",", ".", "!", "[", "]", "(", ")", "'"]:
            return 3
        else:
            return 4

    #If there is a notification message that is unread. 
    if NOTIFICATION_MESSAGE != None and NOTIFICATION_IS_UNREAD:
        NOTIFICATION_IS_UNREAD = False
        
        bitCount = 0
        result = ""
        contentArr = []
        for char in NOTIFICATION_MESSAGE.getContent():
            if (bitCount + getBitWidth(char)) <= 64:
                bitCount += getBitWidth(char)
                result += char
            else:
                contentArr.append(result)
                bitCount = 0
                result = char
        contentArr.append(result.strip())

        result = ""
        for str in contentArr:
            result += str + "\n"

        notification_label_text.text = result

        del result
        del contentArr
        gc.collect()

    # ----------------- Switch between groups ------------------
    if SHOW_NOTIFICATION:
        display.show(notification_group)
    else:
        display.show(group)

    print(f"3: Memory : {gc.mem_free()}")

    

# -------------------------------------------------- Clock : End -------------------------------------------------

# -------------------------------------------------- Loop : Start -------------------------------------------------

last_check = None
last_notification_check = None

while True:
    BLINK = not BLINK

    if not btnUp.value:
        SHOW_DAY_OF_WEEK = not SHOW_DAY_OF_WEEK
    if not btnDown.value:
        NOTIFICATION_IS_NEW = False
        SHOW_NOTIFICATION = not SHOW_NOTIFICATION
    

    if last_check is None or time.monotonic() > last_check + 3600:
        try:
            print("Updating clock...")
            update_clock()
            network.get_local_time()  # Synchronize Board's clock to Internet
            last_check = time.monotonic()
        except RuntimeError as e:
            print("Some error occured, retrying! -", e)
    if (last_notification_check is None or time.monotonic() > last_notification_check + 60): #and time.monotonic() > last_check + 120:
        try:
            print("Checking notifications...")
            check_notifications()
            last_notification_check = time.monotonic()
        except RuntimeError as e:
            print("Error making a request to AWS", e)

    update_clock()
    time.sleep(1)
```

### Behavior

```
Checking notifications...
2: Memory : 28384
3: Memory : 22752
2: Memory : 22448
Traceback (most recent call last):
  File "code.py", line 364, in <module>
  File "code.py", line 261, in update_clock
MemoryError: memory allocation failed, allocating 3072 bytes

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.
```

### Description

Hello! Hoping someone will be able to shine some light on this issue I am having. I am seeing an unusually large decrease in memory when loading two bitmaps consecutively. Note that these bitmaps are 62x32 in resolution and take up only 4 kb in space. However, when I load them consecutively, they cause a memory allocation error despite having over 20kb free...

![image_1_console](https://user-images.githubusercontent.com/37813787/178629737-c4230eda-4d25-45af-b3df-964bcb6096be.png)

Erroring lines:

![image_2_code](https://user-images.githubusercontent.com/37813787/178629739-2c6c1e10-85ec-4e39-a4e1-c358991d2275.png)

I am using the MatrixPortal and the 3mm 64x32 RGB matrix display. 

Please see the attached zip folder which contains my code.py file and secrets.py (personal data redacted) file as well as my font, bmp, and lib directories. The only thing you cannot access is an enclosed API call, but I have commented out those lines and emulated it with some sample data. Zip file: [Potential_memory_leak_when_loading_bitmaps_in_sequence.zip](https://github.com/adafruit/circuitpython/files/9098120/Potential_memory_leak_when_loading_bitmaps_in_sequence.zip)

### Additional information
I am using the MatrixPortal M4 and the 3mm 64x32 RGB matrix display (both bought from Adafruit)

I have added 3 calls to `gc.mem_free()` which outline the memory usage. See Description. 

I have also read the user guide and worked to reduce memory leaks (https://learn.adafruit.com/Memory-saving-tips-for-CircuitPython/additional-tips-and-resources). Having exhausted my options, I posted to the adafruit forums (https://forums.adafruit.com/viewtopic.php?f=60&t=192685&p=932301#p932301). Per the user reply, I have created this report.

**Comment by ladyada** [comment]
hmm those calls create a new ondiskbitmap, which takes up memory, and you probably aren't seeing it freed later, possibly because of :

```
group[0] = displayio.TileGrid(CURRENT_BITMAP1 if BLINK else CURRENT_BITMAP2, pixel_shader=CURRENT_BITMAP1.pixel_shader)
```

you could load all 4 ondiskbitmaps at the beginning and then you can swap them in and out by hiding them. alternatively you may want to try popping them off the group so you can make sure they are gc'd - see the slideshow library which cleanly sweeps between many bitmaps https://github.com/adafruit/Adafruit_CircuitPython_Slideshow/blob/main/adafruit_slideshow.py#L408

**Comment by DJDevon3** [comment]
You're loading displayio.TileGrid(DEFAULT_BITMAP, pixel_shader=DEFAULT_BITMAP.pixel_shader) twice as 2 different variables, it'll work but seem seems unnecessary and redundant.

I think the issue might be stemming from not loading the pixel shader for CURRENT_BITMAP2. It might be trying to use bitmap1 pixel shader on bitmap2 or vice versa. Think of pixel shader as an alpha mask. It shouldn't crash if it's using the wrong pixel shader as long as the other image is loaded. A pixel shader is a required arg for ondiskbitmap. Might be possible to crash it if one of them gets unloaded with a gc and there goes your pixel shader. 
displayio.TileGrid(CURRENT_BITMAP1 if BLINK else CURRENT_BITMAP2, pixel_shader=CURRENT_BITMAP1.pixel_shader)

**Comment by JeremiahDuane** [comment]
> You're loading displayio.TileGrid(DEFAULT_BITMAP, pixel_shader=DEFAULT_BITMAP.pixel_shader) twice as 2 different variables, it'll work but seems redundant and doesn't have anything to do with the main issue in my opinion.

The reason I have two copies of the TIleGrid is I want the grid to populate IMMEDIATELY for a loading screen. To do that, I need it to load before all my labels and BEFORE that method that calculates the time. For this reason, I create the grid and populate the loading screen, and then I pop it off the group after all the loading labels is completed. 

> I think the issue might be stemming from not loading the pixel shader for CURRENT_BITMAP2. It might be trying to use bitmap1 pixel shader on bitmap2 or vice versa. Think of pixel shader as an alpha mask. It shouldn't crash if it's using the wrong pixel shader as long as at least 1 pixel shader for an image stays loaded. A pixel shader is a required arg for ondiskbitmap. Might be possible to crash it if one of them gets unloaded with a gc or for whatever reason, and there goes your pixel shader.

> So I just tried your line of code in my own TFT sketch and the pixel shader is definitely not working correctly in that manner. It looks like a van gogh painting and in 4-bit color. You definitely want to ensure the pixel shader is set for the correct bmp. Honestly it's a really cool effect but I have my doubts about it running like this without crashing. I'm kind of surprised it even works running an if statement inside a tilegrid call.

The reason it works for my use case is both my images are functionally the same in terms of color scheme. The only thing that changes are the POSITIONS of the pixels, not the pixels themselves. 

Example:
![Screenshot 2022-07-13 103036](https://user-images.githubusercontent.com/37813787/178772650-9df1dd7b-2798-44d7-8363-10bc5ed5fa0f.png)

I had to blow up the images so that they were visible as PNGs. The resolution is 32x64px. The pixel shaders for each is truly identical, so I can functionally use either. 

That being said, to prove that this is not the issue, here is an alternative permutation. 

```
    # ----------------- Update Fields : START ------------------
    #Periodically check and see if there is a new season/theme for the scene. 
    #DO NOT RELEASE: Hardcoded as true to test update. 
    if True or (hours == 0 and minutes == 0 and seconds == 0): 
        if minutes % 2 == 0:
            scene = SCENES[2]
        else: 
            scene = SCENES[3]

        print(f"2: Memory : {gc.mem_free()}")
        CURRENT_BITMAP = displayio.OnDiskBitmap(scene.getBMP()) if BLINK else displayio.OnDiskBitmap(scene.getBMP2())
        
        underline_label.color = scene.getPrimaryColor()
        time_label.color = scene.getPrimaryColor()
        date_label.color = scene.getPrimaryColor()
        period_label.color = scene.getPrimaryColor()
        time_label_shadow.color = scene.getSecondaryColor()
        underline_shadow_label.color = scene.getSecondaryColor()
    
    print(f"3: Memory : {gc.mem_free()}")
    group[0] = displayio.TileGrid(CURRENT_BITMAP, pixel_shader=CURRENT_BITMAP.pixel_shader)
    gc.collect()
    print(f"4: Memory : {gc.mem_free()}")
```
Interestingly, this breaks much slower! But still the issue remains. In the moments before breaking, we once again see the stable memory usage (Note that I added a few more prints):

```
2: Memory : 26272
3: Memory : 25936
4: Memory : 29536
3: Memory : 26608
2: Memory : 26272
3: Memory : 22848
4: Memory : 26464
3: Memory : 23872
2: Memory : 23536
Traceback (most recent call last):
  File "code.py", line 366, in <module>
  File "code.py", line 260, in update_clock
MemoryError: memory allocation failed, allocating 3072 bytes

Code done running.

```

> Try using 2 tilegrids and just use an if statement in the loop to display one or the other. I don't think tilegrid likes the way you're trying to setup 2 bitmaps with 1 shader. While it is possible to run 2 bitmaps with 1 shader, if that shader goes bye bye displayio might crash without warning.

As you wish:

```
    #DO NOT RELEASE: Hardcoded as true to test update. 
    if True or (hours == 0 and minutes == 0 and seconds == 0): 
        if minutes % 2 == 0:
            scene = SCENES[2]
        else: 
            scene = SCENES[3]

        print(f"2: Memory : {gc.mem_free()}")
        # CURRENT_BITMAP = displayio.OnDiskBitmap(scene.getBMP()) if BLINK else displayio.OnDiskBitmap(scene.getBMP2())

        CURRENT_BITMAP1 = displayio.OnDiskBitmap(scene.getBMP()) 
        CURRENT_BITMAP2 = displayio.OnDiskBitmap(scene.getBMP2())
        
        underline_label.color = scene.getPrimaryColor()
        time_label.color = scene.getPrimaryColor()
        date_label.color = scene.getPrimaryColor()
        period_label.color = scene.getPrimaryColor()
        time_label_shadow.color = scene.getSecondaryColor()
        underline_shadow_label.color = scene.getSecondaryColor()

    print(f"3: Memory : {gc.mem_free()}")
    if BLINK:
        group[0] = displayio.TileGrid(CURRENT_BITMAP1, pixel_shader=CURRENT_BITMAP1.pixel_shader)
    else:
        group[0] = displayio.TileGrid(CURRENT_BITMAP2, pixel_shader=CURRENT_BITMAP2.pixel_shader)
    gc.collect()
    print(f"4: Memory : {gc.mem_free()}")
```

This fails slightly faster than the second solution, a bit slower than the first. All of these fail within the first 60 seconds, however.

**Comment by tannewt** [comment]
> The only thing that changes are the POSITIONS of the pixels, not the pixels themselves.

Why not just use one TileGrid and bitmap and move it? It is OK for a TileGrid to be out of bounds.

**Comment by JeremiahDuane** [comment]
See image. The position of the pixels change independent of each other. I was saying the count and color of pixels was the same between the images (more or less), I was NOT saying the bmps were identical or could be equal given some vertical or horizontal shift.  All in all, using the same shader works, but is not necessary, as I showed in my adapted code

**Comment by JeremiahDuane** [comment]
I was able to get some very helpful debug output, narrowing down on the issue:

```
code.py output:
    Metro Minimal Clock
Time will be set for America/Chicago
0: Memory : 62752
1: Memory : 41376
#0 | 4642.45
Updating time...
--------------------------------------------------------------------------Even
2: Memory : 37888
2.2: Memory : 34464
2.3: Memory : 31040
3: Memory : 35680
3.1: Memory : 35712
Connecting to AP jgage_netgear
Getting time for timezone America/Chicago
Checking notifications...
--------------------------------------------------------------------------Odd
2: Memory : 27632
2.2: Memory : 27296
2.3: Memory : 26960
3: Memory : 28048
3.1: Memory : 31424
#1 | 4665.93
.
. [HIDING 18 IDENTICAL BLOCKS]
.
#19 | 4835.74
--------------------------------------------------------------------------Odd
2: Memory : 25552
2.2: Memory : 25216
2.3: Memory : 24880
3: Memory : 28608
3.1: Memory : 28912
#20 | 4836.92
--------------------------------------------------------------------------Odd
2: Memory : 25552
2.2: Memory : 25216
2.3: Memory : 24880
3: Memory : 28608
3.1: Memory : 28912
#21 | 4838.1
--------------------------------------------------------------------------Even
2: Memory : 25552
2.2: Memory : 22128
Traceback (most recent call last):
  File "code.py", line 380, in <module>
  File "code.py", line 266, in update_clock
MemoryError: memory allocation failed, allocating 3072 bytes

Code done running.

```

The error always occurs on the first transition between even/odd, e.g. the first time `scene` changes:

```    
    #DO NOT RELEASE: Hardcoded as true to test update. 
    if True or (hours == 0 and minutes == 0 and seconds == 0): 
        if minutes % 2 == 0:
            print(f"--------------------------------------------------------------------------Even")
            scene = SCENES[2]
        else: 
            print(f"--------------------------------------------------------------------------Odd")
            scene = SCENES[3]

        print(f"2: Memory : {gc.mem_free()}")
        bmp = displayio.OnDiskBitmap(scene.getBMP())
        print(f"3: Memory : {gc.mem_free()}")
        bmp2 = displayio.OnDiskBitmap(scene.getBMP2())
        print(f"4: Memory : {gc.mem_free()}")

        CURRENT_BITMAP = bmp if BLINK else bmp2
        # CURRENT_BITMAP = displayio.OnDiskBitmap(scene.getBMP()) if BLINK else displayio.OnDiskBitmap(scene.getBMP2())

        del bmp
        del bmp2
        gc.collect()

        underline_label.color = scene.getPrimaryColor()
        time_label.color = scene.getPrimaryColor()
        date_label.color = scene.getPrimaryColor()
        period_label.color = scene.getPrimaryColor()
        time_label_shadow.color = scene.getSecondaryColor()
        underline_shadow_label.color = scene.getSecondaryColor()

    print(f"5: Memory : {gc.mem_free()}")
    group.pop(0)
    group.insert(0, displayio.TileGrid(CURRENT_BITMAP, pixel_shader=CURRENT_BITMAP.pixel_shader))
    
    del CURRENT_BITMAP
    gc.collect()
    print(f"6: Memory : {gc.mem_free()}")

```

**Comment by tannewt** [comment]
What is line 380 and causing the memory error? It'd be much easier to debug a simpler example.

**Comment by JeremiahDuane** [comment]
> What is line 380 and causing the memory error? It'd be much easier to debug a simpler example.

Its the method call, `update clock`

Again, you can see the full file here: https://codefile.io/f/xj94CjuuCy9k1V0FjQee

**Comment by tannewt** [comment]
> > What is line 380 and causing the memory error? It'd be much easier to debug a simpler example.
> 
> Its the method call, `update clock`
> 
> Again, you can see the full file here: https://codefile.io/f/xj94CjuuCy9k1V0FjQee

That only has 376 lines of code. It must be a slightly different version from the traceback.

> 
> > It'd be much easier to debug a simpler example.
> > You tell me which part of the file is causing the error, and I will take out the rest of the code :-D .
> 
> The tricky thing is, the more code I remove, the less memory is used and the longer it takes to break. For example, if I take the API code out, it takes hours to break.

That sounds like a fragmentation issue. Fragmentation can happen as the free memory occurs in smaller and smaller contiguous chunks. Unfortunately, issues like this are really hard to pin down. Python allocates often under the hood so it can be hard to track every allocation and reference. CircuitPython does have a `memorymonitor` module I added that can help you ensure areas of the code don't allocate: https://docs.circuitpython.org/en/latest/shared-bindings/memorymonitor/index.html It isn't enabled by default though.

**Comment by dhalbert** [comment]
This appears to be a fragmentation issue, as noted in the most recent post. Closing for now.
