### ISSUE TITLE
SDIO not working for Adafruit Grand Central M4 Express with SDIO breakout board

### ISSUE THREAD

**Issue by davepruitt** [adafruit/circuitpython#6914]
### CircuitPython version

```python
Adafruit CircuitPython 7.3.3 on 2022-08-29; Adafruit Grand Central M4 Express with samd51p20
Board ID:grandcentral_m4_express
```

### Code/REPL

```python
import board
import sdioio
import storage

sdcard = sdioio.SDCard(
    clock=board.SDIO_CLOCK,
    command=board.SDIO_COMMAND,
    data=board.SDIO_DATA,
    frequency=25000000)
    
vfs = storage.VfsFat(sdcard)

storage.mount(vfs, "/sd")
```

### Behavior

```python
code.py output:
Traceback (most recent call last):
  File "code.py", line 8, in <module>
ValueError: D32 in use
```

### Description

I have an Adafruit Grand Central M4 Express board wire up to an SDIO breakout board. The wiring is done exactly as shown at the following URL, and I have confirmed there are no issues with the wiring:

https://learn.adafruit.com/adafruit-microsd-spi-sdio/grand-central-sdio-breakout

**Comment by jepler** [comment]
I've reproduced something similar on the samd51 xplained board from microchip. This is with an old random 7.0 alpha, not current.

The first time, an error occurs constructing the `SDCard` object:
```
=== import board
=== import sdioio
=== import storage
=== 
=== sdcard = sdioio.SDCard(
===     clock=board.SDIO_CLOCK,
===     command=board.SDIO_COMMAND,
===     data=board.SDIO_DATA,
===     frequency=25000000)
===     
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
OSError: sd_mmc_check failure: 3
```

Subsequently, (including after restarting the repl), a different error occurs, like the one reported:
```
=== import board
=== import sdioio
=== import storage
=== 
=== sdcard = sdioio.SDCard(
===     clock=board.SDIO_CLOCK,
===     command=board.SDIO_COMMAND,
===     data=board.SDIO_DATA,
===     frequency=25000000)
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
ValueError: D05 in use
```

If an SD card is not present at all, SDCard construction stalls long enough that USB disconnects:
```
[tio 11:26:27] Connected
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-alpha.2-675-g72db13fc2-dirty on 2021-06-09; SAM E54 Xplained Pro with same54p20
>>> 
paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== import board    
=== import sdioio    
=== import storage    
===     
=== sdcard = sdioio.SDCard(    
===     clock=board.SDIO_CLOCK,    
===     command=board.SDIO_COMMAND,    
===     data=board.SDIO_DATA,    
===     frequency=4_000_000)   
=== 

[tio 11:27:02] Disconnected
```
```
