### ISSUE TITLE
floppyio mfm reading is broken on rp2040

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#7662]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.4-32-g6bec65833b-dirty on 2023-02-28; Adafruit Feather RP2040 with rp2040
```

### Code/REPL

```python
# example from adafruit_circuitpython_floppy repo
```

### Behavior

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "floppy_vfs.py", line 41, in <module>
OSError: [Errno 19] No such device
```
(because data read back as all zeros instead of correctly decoding mfm)

**Comment by jepler** [comment]
This is verified working again in 9.2.1 on the floppsy prototype.
