### ISSUE TITLE
BLE HCI _bleio not turned on for Espressif boards

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#7977]
ESP32-S2 and other Espressif boards don't have `_bleio` support for AirLift turned on. I'm not sure if this is an oversight or was done for space-saving reasons.

ESP32-S3 boards have limited native `_bleio` support turned on.

_From a comment by @kairos0ne in https://github.com/adafruit/circuitpython/issues/6930#issuecomment-1546919567_
            

> Why do you restrict the import of the module adafruit_ble if the board is not supported. It seems strange to do such a thing given the market offering of the airlift coprocessor ? 
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 16, in <module>
>   File "adafruit_ble/__init__.py", line 25, in <module>
> ImportError: no module named '_bleio'
> ```
>

**Comment by dhalbert** [comment]
Enabling this is not simple, due to the way `py/circuitpy_defns.mk`. The Makefile logic there assumes that the port-specific implementation of a native module is in `ports/*/common-hal/<themodule>`. HCI `_bleio` is special-cased as being in `devices/ble_hci/common-hal`. But in Espressif, there is a native `_bleio` under ports. So the logic around `SRC_PATTERN` gets confused, and both sets of files get compiled, causing linking issues later.

`SRC_PATTERN` is also used to pick up `shared-bindings/<themodule>`.

The generic `touchio` vs native `touchio` is a similar case gets around this by disabling the source in one set of files with special `#if`s, which was something of a hack solution. I tried something similar with `_bleio`, but it's more pervasive, and I still ran into issues due to the special location of the sources in `devices/...` (handled by a `vpath`), and also because the Espressif BLE libraries were still being required (even though they don't exist for ESP32-S2, etc.). I tried working around the latter too, unsuccessfully (I don't remember the details).

I think `circuitpy_defins.mk` and `SRC_PATTERNS` need to be restructured to specify the source location more explicitly. That is a lot of work. So I am going to push this to Long Term, since there has been only one request to use AirLift BLE with Espressif boards. We will make it clearer that doesn't work. AirLift BLE is very limited anyway right now -- it can only be a peripheral.
