### ISSUE TITLE
ESP32-C6-DevKitC-1 v1.2 Flashing successful, but CP doesn't boot?

### ISSUE THREAD

**Issue by messwiththebest1995** [adafruit/circuitpython#8585]
Hi,

Recently bought a couple Espressif ESP32-C6-DevKitC-1. Tried installing CP, but hit an issue of some kind.

I can build/flash examples from ESP-IDF, but flashing CP's .bin to 0x0 or 0x10000 doesn't start CP.

When powered, the LED flashes GREEN once every few seconds (RPLE success?).

Board brand: Espressif
Board model: ESP32-C6-DevKitC-1 v1.2
ESP32 board: ESP32-C6-WROOM-1 (bottom left beside QR says MAN8)

```bash
esptool --chip esp32c6 --port COM5 write_flash 0x0 adafruit-circuitpython-espressif_esp32c6_devkitc_1_n8-en_US-9.0.0-alpha.2.bin
esptool.py v4.7.dev3
Serial port COM5
Connecting....
Chip is ESP32-C6 (QFN40) (revision v0.0)
Features: WiFi 6, BT 5, IEEE802.15.4
Crystal is 40MHz
MAC: ---
BASE MAC: ---
MAC_EXT: ---
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Flash will be erased from 0x00000000 to 0x001a5fff...
Compressed 1727520 bytes to 1071461...
Wrote 1727520 bytes (1071461 compressed) at 0x00000000 in 94.3 seconds (effective 146.5 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
```

Afterwards, connecting using PuTTY as Serial returns:

```bash
ESP-ROM:esp32c6-20220919
Build:Sep 19 2022
rst:0x1 (POWERON),boot:0x1e (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:2
load:0x4086c410,len:0xb98
load:0x4086e610,len:0x233c
load:0x40875728,len:0xd4
entry 0x4086c410
```

I'm willing to compile if it can help troubleshoot. ;)

**Comment by bill88t** [comment]
Are you connected to the "USB" port?

**Comment by bill88t** [comment]
C6 cannot show a usb filesystem. The "USB" port is only capable of serial + jtag for debugging.
The "UART" port is just attached to some of the board's gpio.

**Comment by FrozenGalaxy** [comment]
Sorry to necro, im a beginner at this stuff,
I fail to even flash it:
```
esptool --chip esp32c6 -p COM17 write_flash 0x0 adafruit-circuitpython-espressif_esp32c6_devkitm_1_n4-en_US-9.1.0-beta.4.bin
esptool.py v4.7.0
Serial port COM17
Connecting...
Chip is ESP32-C6FH4 (QFN32) (revision v0.0)
Features: WiFi 6, BT 5, IEEE802.15.4
Crystal is 40MHz
MAC: 54:32:04:ff:fe:03:33:90
BASE MAC: 54:32:04:03:33:90
MAC_EXT: ff:fe
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Flash will be erased from 0x00000000 to 0x0016dfff...
Compressed 1496128 bytes to 922057...
Writing at 0x000289ea... (8 %)Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\esptool\__init__.py", line 1139, in _main
    main()
  File "C:\Python312\Lib\site-packages\esptool\__init__.py", line 923, in main
    operation_func(esp, args)
  File "C:\Python312\Lib\site-packages\esptool\cmds.py", line 598, in write_flash
    esp.flash_defl_block(block, seq, timeout=timeout)
  File "C:\Python312\Lib\site-packages\esptool\loader.py", line 131, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\esptool\loader.py", line 1077, in flash_defl_block
    self.check_command(
  File "C:\Python312\Lib\site-packages\esptool\loader.py", line 467, in check_command
    val, data = self.command(op, data, chk, timeout=timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\esptool\loader.py", line 436, in command
    p = self.read()
        ^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\esptool\loader.py", line 369, in read
    return next(self._slip_reader)
           ^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

A fatal error occurred: The chip stopped responding
``` 
and how would you write circuit python files onto said drive after?

**Comment by tannewt** [comment]
Please ask on the Discord: https://adafru.it/discord This isn't the place to get help. It is where you file issues to track what needs to be changed.
