### ISSUE TITLE
Format Specifiers for binary representation of integers fails if using '_' separator 

### ISSUE THREAD

**Issue by someyob** [adafruit/circuitpython#8837]
### CircuitPython version

```python
Adafruit CircuitPython 8.2.9 on 2023-12-06; Raspberry Pi Pico with rp2040
```

### Code/REPL

```python
>>> print(f'{63456:,}')
63,456
>>> print(f'{63456:b}')
1111011111100000
>>> print(f'{63456:_b}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid format specifier
>>>
```

### Behavior

>>> print(f'{63456:,}')
63,456
>>> print(f'{63456:b}')
1111011111100000
>>> print(f'{63456:_b}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid format specifier
>>> 

### Description

The '_' separator for formatting an integer as a binary (string) was included in Python 3.4 (afaik), but it fails in CircuitPython.

**Comment by jepler** [comment]
I went ahead and marked this as an enhancement request, but I also implemented it and offered it to upstream at https://github.com/micropython/micropython/pull/13516 -- I think this could be very useful and would like to see it added.
