### ISSUE TITLE
Pico 2 W: Bluetooth not working (CircuitPython 9.2.1)

### ISSUE THREAD

**Issue by Anoyomouse** [adafruit/circuitpython#9843]
### CircuitPython version

```python
Adafruit CircuitPython 9.2.1 on 2024-11-20; Raspberry Pi Pico 2 W with rp2350a
```

### Code/REPL

```python
from adafruit_ble import BLERadio
ble = BLERadio()
```

### Behavior

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_ble/__init__.py", line 166, in __init__
RuntimeError: No adapter available
```

### Description

Bluetooth adaptor not found in pico 2 w port
I've looked at the configs and everything is the same as the pico w port, unless something is missing in the PI SDK

**Comment by jepler** [comment]
Hi & thanks for your report! This is expected: bluetooth support is not yet implemented in circuitpython for the pico w or pico 2 w.

If you like, you can subscribe to notifications on the existing feature request: https://github.com/adafruit/circuitpython/issues/7693
